### KFold

In [4]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

/Users/sieunbae/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [5]:
iris = load_iris()

In [14]:
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state = 156)
print(features)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [12]:
kfold = KFold(n_splits = 5)
cv_accuracy = []

In [19]:
n_iter = 0

for train_idx, test_idx in kfold.split(features):
    #kfold.split(sth)은 폴드를 split한 train, test 인덱스를 반환함
    #print(train_idx, test_idx)
    #print(features[[0, 1, 2]]) index는 리스트로 전달 가능
    
    X_train, X_test = features[train_idx], features[test_idx]
    y_train, y_test = label[train_idx], label[test_idx]
    
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차검증정확도 :{1}, 학습데이터크기 :{2}, 검증데이터크기 :{3}'.format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증세트인덱스 :{1}'.format(n_iter, test_idx))
    cv_accuracy.append(accuracy)


#1 교차검증정확도 :1.0, 학습데이터크기 :120, 검증데이터크기 :30
#1 검증세트인덱스 :[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차검증정확도 :0.9667, 학습데이터크기 :120, 검증데이터크기 :30
#2 검증세트인덱스 :[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차검증정확도 :0.8667, 학습데이터크기 :120, 검증데이터크기 :30
#3 검증세트인덱스 :[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차검증정확도 :0.9333, 학습데이터크기 :120, 검증데이터크기 :30
#4 검증세트인덱스 :[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차검증정확도 :0.7333, 학습데이터크기 :120, 검증데이터크기 :30
#5 검증세트인덱스 :[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]


In [20]:
print('\n## 평균검증정확도:', np.mean(cv_accuracy))


## 평균검증정확도: 0.9


### Stratified KFold

In [44]:
#불균등한 분포를 띠는 데이터에 대한 교차검증
import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(data = iris.data, columns = iris.feature_names)
iris_df['label'] = iris.target
iris_df['label'].value_counts()

#df.loc[:, df.columns != col]
print(iris_df)
print(iris_df.loc[:, iris_df.columns != 'label'])

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1

In [30]:
kfold = KFold(n_splits = 3)
n_iter = 0
for train_idx, test_idx in kfold.split(iris_df):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_idx]
    label_test = iris_df['label'].iloc[test_idx]
    print('## 교차 검증: {0}'.format(n_iter))
    print('학습레이블데이터분포:\n', label_train.value_counts())
    print('\n')
    print('검증레이블데이터분포:\n', label_test.value_counts())
    print('\n')
    

## 교차 검증: 1
학습레이블데이터분포:
 2    50
1    50
Name: label, dtype: int64


검증레이블데이터분포:
 0    50
Name: label, dtype: int64


## 교차 검증: 2
학습레이블데이터분포:
 2    50
0    50
Name: label, dtype: int64


검증레이블데이터분포:
 1    50
Name: label, dtype: int64


## 교차 검증: 3
학습레이블데이터분포:
 1    50
0    50
Name: label, dtype: int64


검증레이블데이터분포:
 2    50
Name: label, dtype: int64




In [49]:
from sklearn.model_selection import StratifiedKFold

skf = KFold(n_splits = 3)
n_iter = 0

for train_idx, test_idx in skf.split(iris_df, iris_df['label']):
    #아래를 통해 하나의 레이블이 전혀 포함되지 않은 폴드들이 생성되었음을 확인
    
    #n_iter += 1
    label_train = iris_df['label'].iloc[train_idx]
    label_test = iris_df['label'].iloc[test_idx]
    print('## 교차 검증: {0}'.format(n_iter))
    print('학습레이블데이터분포:\n', label_train.value_counts())
    print('\n')
    print('검증레이블데이터분포:\n', label_test.value_counts())
    print('\n')
    
    train_df = iris_df.loc[:, iris_df.columns != 'label']
    
    #학습하지 못한 레이블이 있을 때 정확도는 어떨지 확인 => accuracy = 0.0
    X_train, X_test = train_df.iloc[train_idx], train_df.iloc[test_idx]
    y_train, y_test = iris_df['label'].iloc[train_idx], iris_df['label'].iloc[test_idx]
    
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차검증정확도 :{1}, 학습데이터크기 :{2}, 검증데이터크기 :{3}'.format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증세트인덱스 :{1}'.format(n_iter, test_idx))
    cv_accuracy.append(accuracy)
    
    print(cv_accuracy)

## 교차 검증: 0
학습레이블데이터분포:
 2    50
1    50
Name: label, dtype: int64


검증레이블데이터분포:
 0    50
Name: label, dtype: int64



#1 교차검증정확도 :0.0, 학습데이터크기 :100, 검증데이터크기 :50
#1 검증세트인덱스 :[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[0.98, 0.94, 0.98, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.98, 0.94, 0.98, 0.98, 0.94, 0.98, 0.0]
## 교차 검증: 1
학습레이블데이터분포:
 2    50
0    50
Name: label, dtype: int64


검증레이블데이터분포:
 1    50
Name: label, dtype: int64



#2 교차검증정확도 :0.0, 학습데이터크기 :100, 검증데이터크기 :50
#2 검증세트인덱스 :[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]
[0.98, 0.94, 0.98, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.98, 0.94, 0.98, 0.98, 0.94, 0.98, 0.0, 0.0]
## 교차 검증: 2
학습레이블데이터분포:
 1    50
0    50
Name: label, dtype: int64


검증레이블데이터분포:
 2    50
Name: label, dtype: int64



#3 교차검증정확도 :0.0, 학습데이터크기 :100, 검증데이터크기 :

In [34]:
dt_clf = DecisionTreeClassifier(random_state = 156)

skfold = StratifiedKFold(n_splits=3)
n_iter = 0
cv_accuracy = []

for train_idx, test_idx in skf.split(features, label):
    X_train, X_test = features[train_idx], features[test_idx]
    y_train, y_test = label[train_idx], label[test_idx]
    
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차검증정확도 :{1}, 학습데이터크기 :{2}, 검증데이터크기 :{3}'.format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증세트인덱스 :{1}'.format(n_iter, test_idx))
    cv_accuracy.append(accuracy)


#1 교차검증정확도 :0.98, 학습데이터크기 :100, 검증데이터크기 :50
#1 검증세트인덱스 :[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차검증정확도 :0.94, 학습데이터크기 :100, 검증데이터크기 :50
#2 검증세트인덱스 :[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차검증정확도 :0.98, 학습데이터크기 :100, 검증데이터크기 :50
#3 검증세트인덱스 :[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]


In [35]:
print('\n## 교차검증별정확도: ', np.round(cv_accuracy, 4))
print('\n## 평균검증정확도:', np.mean(cv_accuracy))


## 교차검증별정확도:  [0.98 0.94 0.98]

## 평균검증정확도: 0.9666666666666667


#### => fold 세트 설정 -> 반복을 통해 학습,테스트 데이터의 인덱스 추출 -> 학습,예측 수행, 예측성능 반환

### cross_val_score(estimator, X, y=None, scoring=None, cv=None, n_jobs=1, verbose=0, fit_params=None)
- 기본적으로 classifier에서는 StratifiedKFold

In [50]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

In [51]:
iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state = 156)

data = iris_data.data
label = iris_data.target

In [53]:
#내부에서 fit, predict, evaluate 시켜줌
scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
print(scores)

[0.98 0.94 0.98]
