In [2]:
import numpy as np

In [3]:
array1= np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 형태:', array1.shape)

array1 type: <class 'numpy.ndarray'>
array1 형태: (3,)


In [5]:
array2= np.array([[1,2,3],
                [2,3,4]])
print('array2 type:', type(array2))
print('array2 형태:', array2.shape)

array2 type: <class 'numpy.ndarray'>
array2 형태: (2, 3)


In [7]:
array3= np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 형태:', array3.shape)

array3 type: <class 'numpy.ndarray'>
array3 형태: (1, 3)


In [9]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


#### ndarray 생성

In [10]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [11]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [12]:
one_array = np.ones((3,2), dtype='int32')
print(one_array)
print(one_array.dtype, one_array.shape)

[[1 1]
 [1 1]
 [1 1]]
int32 (3, 2)


#### ndarray 차원/크기 변경

In [14]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [15]:
array4 = array1.reshape(-1, 5)
print('array4:\n', array4)
print('array4 shape:', array4.shape)

array4:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array4 shape: (2, 5)


In [16]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [17]:
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape) #차원 축소

array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)


In [18]:
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape) #차원 확장

array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


#### indexing

In [19]:
type(array6[1:][:])

numpy.ndarray

In [20]:
array6[1:] #fancy indexing

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [21]:
array1d = np.arange(start=1, stop=10)
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값:', array3)

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


In [22]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [23]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])

In [24]:
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [25]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


#### 행렬의 정렬

In [28]:
org_array = np.array([3,1,9,5])
print('원본 행렬: ', org_array)

sort_array1 = np.sort(org_array)
print(sort_array1)

sort_array2 = org_array.sort()
print(sort_array2)
print(org_array)

원본 행렬:  [3 1 9 5]
[1 3 5 9]
None
[1 3 5 9]


In [31]:
sort_array1_desc = np.sort(org_array)[::-1]
print(sort_array1_desc)

[9 5 3 1]


In [32]:
array2d = np.array([[8,12],
                   [7,1]])
#행중심
sort_array2d_axis0 = np.sort(array2d, axis=0)
print(sort_array2d_axis0) #로우 방향 |

sort_array2d_axis1 = np.sort(array2d, axis=1)
print(sort_array2d_axis1) #칼럼 방향 ->

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


#### 정렬된 행렬의 인덱스를 반환하기