### Label Encoding
- 문자열값 -> 숫자형 카테고리값
- 알고리즘이 숫자에 가중치를 두는 경우 문제 발생 (트리의 경우 ㄱㅊ)

In [1]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [2]:
encoder = LabelEncoder()

encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [3]:
print('인코딩 클래스:', encoder.classes_)

['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [5]:
print('디코딩 원본값:', encoder.inverse_transform([4,5,2,0,1,1,3,3]))
print(encoder.inverse_transform(labels))

디코딩 원본값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']
['TV' '냉장고' '전자레인지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서']


### OneHot Encoding
- 숫자형으로 변환되어있어야 함
- 입력 값으로 2차원 데이터가 필요

In [7]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [11]:
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(labels)

labels = labels.reshape(-1, 1)
print(labels)

[0 1 4 5 3 3 2 2]
[[0]
 [1]
 [4]
 [5]
 [3]
 [3]
 [2]
 [2]]


In [13]:
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('인코딩 데이터:',oh_labels.toarray())
print('인코딩 데이터 차원:',oh_labels.shape)

인코딩 데이터: [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
인코딩 데이터 차원: (8, 6)


#### pandas에서 get_dummies라는 함수 제공. 바로 one hot encoding

In [14]:
import pandas as pd

df = pd.DataFrame({'item': ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})
print(df)

    item
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서


In [15]:
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

### feature scaling

#### Standard Scaler
- SVM, Linear Regression, Logistic Regression

In [16]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

In [17]:
print('평균:', iris_df.mean())
print('분산:', iris_df.var())

평균: sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
분산: sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [18]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df) #return numpy
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

In [19]:
print('평균:', iris_df_scaled.mean())
print('분산:', iris_df_scaled.var())

평균: sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
분산: sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


#### MinMaxScaler
- (0,1) 로 정규화, 음수 존재할 경우 (-1, 1)

In [21]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

In [22]:
print('최대:', iris_df_scaled.max())
print('최소:', iris_df_scaled.min())

최대: sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
최소: sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64


#### test 데이터에는 fit하면 안됨. train에 fit한 것을 기준으로 테스트 진행

In [23]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

In [24]:
train_array = np.arange(0,11).reshape(-1, 1)
test_array = np.arange(0,6).reshape(-1, 1)

In [26]:
scaler = MinMaxScaler() #feature_range 파라미터를 통해 범위 지정 가능

scaler.fit(train_array) #최대,최솟값 설정
train_scaled = scaler.transform(train_array)

print('원본:', np.round(train_array.reshape(-1),2))
print('scale:', np.round(train_scaled.reshape(-1), 2))

원본: [ 0  1  2  3  4  5  6  7  8  9 10]
scale: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [27]:
scaler.fit(test_array)
test_scaled = scaler.transform(test_array)

print('원본:', np.round(test_array.reshape(-1),2))
print('scale:', np.round(test_scaled.reshape(-1), 2)) #잘못 scale됨

원본: [0 1 2 3 4 5]
scale: [0.  0.2 0.4 0.6 0.8 1. ]


In [28]:
scaler = MinMaxScaler() #feature_range 파라미터를 통해 범위 지정 가능

scaler.fit(train_array) #최대,최솟값 설정
train_scaled = scaler.transform(train_array)

print('원본:', np.round(train_array.reshape(-1),2))
print('scale:', np.round(train_scaled.reshape(-1), 2))

test_scaled = scaler.transform(test_array)

print('원본:', np.round(test_array.reshape(-1),2))
print('scale:', np.round(test_scaled.reshape(-1), 2))

원본: [ 0  1  2  3  4  5  6  7  8  9 10]
scale: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
원본: [0 1 2 3 4 5]
scale: [0.  0.1 0.2 0.3 0.4 0.5]


#### => 데이터세트 분리 전 전체에 대해 scale 후 분리하는 것이 바람직